# Generated by Django 5.2.4 on 2025-07-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('irrenunciable', models.BooleanField(default=False)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feriado (Cache)',
                'verbose_name_plural': 'Feriados (Cache)',
                'ordering': ['fecha'],
            },
        ),
    ]
